### ISSUE TITLE
Sign in for non-existing user doesn't return errors

### ISSUE THREAD

**Issue by vfonic** [evilmartians/chronicles-gql-martian-library#2]
I noticed that, in the second part of the tutorial (https://evilmartians.com/chronicles/graphql-on-rails-2-updating-the-data) when logging in with non-existing user (email), the guide says the app will return errors, but it doesn't. It just returns the empty data:
https://github.com/evilmartians/chronicles-gql-martian-library/blob/master/app/graphql/mutations/sign_in_mutation.rb#L9-L10

> Our “lucky path” seems to be working. What if we try to sign in using a wrong email? The worst thing that could happen is an error in the browser console:

![](https://cdn.evilmartians.com/front/posts/graphql-on-rails-2-updating-the-data/wrong_email-d5986e1.png)

The above is a screenshot for the guide. Here's my Google Chrome screenshot:
<img width="1085" alt="Screen Shot 2019-06-22 at 13 28 23" src="https://user-images.githubusercontent.com/67437/59960362-b4a12680-94f1-11e9-8c6d-77e9856f2967.png">

How do you usually deal with these cases in your applications? Do you return an error to the user and then deal with it in rejected promise `.catch`? Or do you do something like:

```jsx
<Query query={Me}>
  {({ data, loading, error }) => {
    if (loading) return 'Loading...';
    if (error) return 'Error: ' + error;
    // render the "happy path"
  }}
</Query>
```

**Comment by DmitryTsepelev** [comment]
Nice catch! We decided to discuss error handling in the third part of the tutorial, so for now your code should just do nothing. I'll update the article text shortly, and let's discuss a way of handling errors as soon as the third part arrives

**Comment by vfonic** [comment]
@DmitryTsepelev thanks! I'll be on the lookout for the third part in the series!

Since there's no real actionable tasks here, apart from making third part in the series, I'll close this issue.
