### ISSUE TITLE
babel-polyfill is deprecated

### ISSUE THREAD

**Issue by AlexeyMatskevich** [evilmartians/chronicles-gql-martian-library#3]
Hi guys, I studied your repository and tried to reproduce. When I started the server I found a warning about babel-polyfill, which have recommended use core-js instead of the deprecated package. Then I found that's core-js already included and have a setting in `babel.config.js` by default. What do you think about remove babel-polyfill?

**Comment by HellSquirrel** [comment]
@AlexeyMatskevich This is a great idea! Thank you. We forgot to remove it after switching to webpacker 4 :)
