### ISSUE TITLE
Typo in app/javascript/components/Library/index.js

### ISSUE THREAD

**Issue by travisdock** [evilmartians/chronicles-gql-martian-library#8]
In Part 2 of the blog, in the section where the UpdateItemForm is added to the Library component, there is an extra `;` that results in an unexpected token error.
![Screen Shot 2019-08-09 at 7 19 28 AM](https://user-images.githubusercontent.com/36681963/62778504-29b2c600-ba76-11e9-92fc-1203c96f9864.png)

Also, the path at the top of the example should be `Library/index.js` and not `Library.js`

**Comment by DmitryTsepelev** [comment]
Hi @travisdock, thank you for the report! I've fixed these typos
